const products = 
[
    {
        _id: '1',
        name: 'Áo công sở huyền bí',
        slug: 'Áo-công-sở-huyền-bí',
        category: 'Áo Sơ Mi',
        categorySlug: 'ao-so-mi',
        countInStock: 10,
        image_main: '/images/Blouse001.jpg',
        image01: '/images/Blouse002.jpg',
        image02: '/images/Blouse003.jpg',
        price: 292,
        pricesell: 351,
        color: ["Baby Blue", "Red",],
        size: ["S", "L", "XL"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '2',
        name: 'Áo công sở nữ tính',
        slug: 'Áo-công-sở-nữ-tính',
        category: 'Áo Sơ Mi',
        categorySlug: 'ao-so-mi',
        countInStock: 0,
        image_main: '/images/Blouse004.jpg',
        image01: '/images/Blouse005.jpg',
        image02: '/images/Blouse006.jpg',
        price: 381,
        pricesell: 422,
        color: ["Pink", "Flamingo", "Orange"],
        size: ["S", "M", "L"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '3',
        name: 'Áo dạo phố cuối thu',
        slug: 'Áo-dạo-phố-cuối-thu',
        category: 'Áo Sơ Mi',
        categorySlug: 'ao-so-mi',
        countInStock: 7,
        image_main: '/images/Blouse007.jpg',
        image01: '/images/Blouse008.jpg',
        image02: '/images/Blouse009.jpg',
        price: 279,
        pricesell: 300,
        color: ["Light Gray", "Medium Gray"],
        size: ["M", "L", "XL"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '4',
        name: 'Áo công sở kiểu mẫu',
        slug: 'Áo-công-sở-kiểu-mẫu',
        category: 'Áo Sơ Mi',
        categorySlug: 'ao-so-mi',
        countInStock: 10,
        image_main: '/images/Blouse012.jpg',
        image01: '/images/Blouse011.jpg',
        image02: '/images/Blouse010.jpg',
        price: 307,
        pricesell: 324,
        color: ["White", "Blue"],
        size: ["S"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '5',
        name: 'Váy dạ hội tinh xảo',
        slug: 'Váy-dạ-hội-tinh-xảo',
        category: 'Váy Liền Thân',
        categorySlug: 'vay-lien-than',
        countInStock: 3,
        image_main: '/images/Dress002.jpg',
        image01: '/images/Dress001.jpg',
        image02: '/images/Dress003.jpg',
        price: 358,
        pricesell: 384,
        color: ["Black"],
        size: ["S", "M", "L", "XL"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '6',
        name: 'Váy đi cafe cùng crush',
        slug: 'Váy-đi-cafe-cùng-crush',
        category: 'Váy Liền Thân',
        categorySlug: 'vay-lien-than',
        countInStock: 6,
        image_main: '/images/Dress005.jpg',
        image01: '/images/Dress004.jpg',
        image02: '/images/Dress006.jpg',
        price: 318,
        pricesell: 334,
        color: ["Shushine", "Yellow", "Athletic Gold"],
        size: ["S", "M", "L"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '7',
        name: 'Váy hồng nhìn là yêu',
        slug: 'Váy-hồng-nhìn-là-yêu',
        category: 'Váy Liền Thân',
        categorySlug: 'vay-lien-than',
        countInStock: 14,
        image_main: '/images/Dress008.jpg',
        image01: '/images/Dress007.jpg',
        image02: '/images/Dress009.jpg',
        price: 207,
        pricesell: 248,
        color: ["Pink", "Berry"],
        size: ["S", "M","XL"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '8',
        name: 'Váy liền thân tôn dáng',
        slug: 'Váy-liền-thân-tôn-dáng',
        category: 'Váy Liền Thân',
        categorySlug: 'vay-lien-than',
        countInStock: 16,
        image_main: '/images/Dress010.jpg',
        image01: '/images/Dress010.jpg',
        image02: '/images/Dress012.jpg',
        price: 241,
        pricesell: 268,
        color: ["Pink", "Flamingo"],
        size: ["S", "M", "L", "XL"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '9',
        name: 'Giày cao gót dạ hội',
        slug: 'Giày-cao-gót-dạ-hội',
        category: 'Giày',
        categorySlug: 'giay',
        countInStock: 7,
        image_main: '/images/High_heels002.jpg',
        image01: '/images/High_heels001.jpg',
        image02: '/images/High_heels003.jpg',
        price: 149,
        pricesell: 200,
        color: ["Gray"],
        size: ["S", "L", "XL"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '10',
        name: 'Đầm ngủ sexy',
        slug: 'Đầm-ngủ-sexy',
        category: 'Đầm Ngủ',
        categorySlug: 'dam-ngu',
        countInStock: 8,
        image_main: '/images/Nightie001.jpg',
        image01: '/images/Nightie002.jpg',
        image02: '/images/Nightie003.jpg',
        price: 377,
        pricesell: 424,
        color: ["Black", "Navy"],
        size: ["S", "M", "L"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '11',
        name: 'Ren cực mỏng khó tả',
        slug: 'Ren-cực-mỏng-khó-tả',
        category: 'Đầm Ngủ',
        categorySlug: 'dam-ngu',
        countInStock: 5,
        image_main: '/images/Nightie007.jpg',
        image01: '/images/Nightie006.jpg',
        image02: '/images/Nightie005.jpg',
        price: 418,
        pricesell: 442,
        color: ["Black", "Gray"],
        size: ["S", "M", "L"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '12',
        name: 'Váy gấp xám xinh xẻo',
        slug: 'Váy-gấp-xám-xinh-xẻo',
        category: 'Váy',
        categorySlug: 'vay',
        countInStock: 0,
        image_main: '/images/Skirt001.jpg',
        image01: '/images/Skirt002.jpg',
        image02: '/images/Skirt003.jpg',
        price: 172,
        pricesell: 214,
        color: ["Black", "Gray"],
        size: ["S", "M",],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '13',
        name: 'Váy tím dạ hội',
        slug: 'Váy-tím-dạ-hội',
        category: 'Váy',
        categorySlug: 'vay',
        countInStock: 0,
        image_main: '/images/Skirt004.jpg',
        image01: '/images/Skirt008.jpg',
        image02: '/images/Skirt005.jpg',
        price: 245,
        pricesell: 314,
        color: ["Black"],
        size: ["S", "XL"],
        description: 'mô tả sản phẩm',
    },
    {
        _id: '14',
        name: 'Quần cotton thoáng mát',
        slug: 'Quần-cotton-thoáng-mát',
        category: 'Quần',
        categorySlug: 'quan',
        countInStock: 1,
        image_main: '/images/Trousser001.jpg',
        image01: '/images/Trousser002.jpg',
        image02: '/images/Trousser003.jpg',
        price: 172,
        pricesell: 219,
        color: ["Blue", "Black"],
        size: ["M", "XL"],
        description: 'mô tả sản phẩm',
    },
]

const getAllProducts = () => products

const getProducts = (count) => {
    const max = products.length - count
    const start = Math.floor(Math.random() * max)
    return products.slice(start, start + count)
}

const getProductBySlug = (slug) => products.find(e => e.slug === slug)

const getCartItemsInfo = (cartItems) => {
    let res = []
    if (cartItems.length > 0) {
        cartItems.forEach(e => {
            let product = getProductBySlug(e.slug)
            res.push({
                ...e,
                product: product
            })
        })
    }
    return res.sort((a, b) => a.id > b.id ? 1 : (a.id < b.id ? -1 : 0))
}

const productData = {
    getAllProducts,
    getProducts,
    getProductBySlug,
    getCartItemsInfo
}

export default productData;
